---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acs-hub-auth
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
    resourceNames:
      - admission-control-tls
      - collector-tls
      - sensor-tls

  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - get
      - watch
      - list
