---
apiVersion: operator.openshift.io/v1
kind: SecondaryScheduler
metadata:
  ## This must be named cluster -- boo design
  name: cluster
  namespace: openshift-secondary-scheduler-operator
spec:
  logLevel: Normal
  operatorLogLevel: Normal
  managementState: Managed
  schedulerConfig: scheduler-noderesourcesfit-disabled
