---
apiVersion: v1
data: '{{hub (eq (index $.ManagedClusterLabels "local-cluster") "true") | skipObject hub}}{{hub copySecretData "stackrox" "admission-control-tls" hub}}'
kind: Secret
metadata:
  labels:
    certificate_key_name: admission-control-cert.pem
  name: admission-control-tls
  namespace: stackrox
type: Opaque
