---
apiVersion: v1
data: '{{ (eq "{{hub (index $.ManagedClusterLabels `local-cluster`) hub}}" "true") | skipObject }}{{hub copySecretData "stackrox" "collector-tls" hub}}'
kind: Secret
metadata:
  labels:
    certificate_key_name: collector-cert.pem
  name: collector-tls
  namespace: stackrox
type: Opaque
